# Generated by Django 4.1.6 on 2023-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(max_length=2000, null=True, verbose_name='Описание товара')),
                ('image', models.CharField(max_length=300, verbose_name='Фото')),
                ('category', models.CharField(choices=[('Alcohol', 'Алкоголь'), ('Smartphone', 'Смартфон'), ('Cars', 'Машины'), ('Other', 'Разное')], default='Other', max_length=60, verbose_name='Категория')),
                ('remaining', models.IntegerField(verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Дата и время удаления')),
            ],
        ),
    ]
